### ISSUE TITLE
it doesn't work for me at all 

### ISSUE THREAD

**Issue by hamidashoor** [CentaurWarchief/react-native-android-sms-listener#56] opened 2020-11-13 17:01 UTC
i installed the package  of `react-native-android-sms-listener` 
and this is my code in a Function  :
```
  SmsRetriever.addSmsListener(event => {
          alert(event.message);
          SmsRetriever.removeSmsListener();
        }); 
```

and when I press a bottom, this code runs...

and i didn't get any alert in my application

**Comment by lucasalexandre-cc** [comment] 2020-11-14 19:42
Here is not working too. Someone could help?

`
function getPermission() {
    return PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.READ_SMS,
      {
        title: "Ola",
        message: "Permissão para ver seu sms rss."
      }
    );
  }

async function listenSms() {
    const resp = await getPermission();
    console.log(resp);
    const lister = SmsListener.addListener(message => {
      console.log(message);
      addMessage(message.body);
    });

    setSmsListner(lister);
  }
`

**Comment by lucasalexandre-cc** [comment] 2020-11-14 19:46
Here is not working too. 

```
function getPermission() {
    return PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.READ_SMS,
      {
        title: "Ola",
        message: "Permissão para ver seu sms rss."
      }
    );
  }

  async function listenSms() {
    const resp = await getPermission();
    console.log(resp);
    const lister = SmsListener.addListener(message => {
      console.log(message);
      addMessage(message.body);
    });
    setSmsListner(lister);
  }
```
I receive granted permission, test send sms but the listener is not working.

**Comment by lucasalexandre-cc** [comment] 2020-11-14 19:55
> Here is not working too.
> 
> ```
> function getPermission() {
>     return PermissionsAndroid.request(
>       PermissionsAndroid.PERMISSIONS.READ_SMS,
>       {
>         title: "Ola",
>         message: "Permissão para ver seu sms rss."
>       }
>     );
>   }
> 
>   async function listenSms() {
>     const resp = await getPermission();
>     console.log(resp);
>     const lister = SmsListener.addListener(message => {
>       console.log(message);
>       addMessage(message.body);
>     });
>     setSmsListner(lister);
>   }
> ```
> 
> I receive granted permission, test send sms but the listener is not working.

I solve this problem, sorry. I only need to ask for "RECEIVE_SMS" permission too.

```
async function getPermission() {
    await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.READ_SMS,
      {
        title: "Ola",
        message: "Permissão para ver seu sms rss."
      }
    );

    await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.RECEIVE_SMS, {
      title: 'Receive SMS',
      message: 'Need access to receive sms, to verify OTP'
    }
    );
  }
```

**Comment by novonimo** [comment] 2020-12-07 19:44
> 
> I solve this problem, sorry. I only need to ask for "RECEIVE_SMS" permission too.
> 
> ```
> async function getPermission() {
>     await PermissionsAndroid.request(
>       PermissionsAndroid.PERMISSIONS.READ_SMS,
>       {
>         title: "Ola",
>         message: "Permissão para ver seu sms rss."
>       }
>     );
> 
>     await PermissionsAndroid.request(
>       PermissionsAndroid.PERMISSIONS.RECEIVE_SMS, {
>       title: 'Receive SMS',
>       message: 'Need access to receive sms, to verify OTP'
>     }
>     );
>   }
> ```



don't forget to add **READT_SMS** and **RECEIVE_SMS** permissions to your **AndroidManifest.xml** too.

**Comment by sudo-vaibhav** [comment] 2021-06-23 08:33
can we close this issue now since the problem is solved?

**Closed as completed** 2021-06-23 16:36 UTC
